config/routes.rb
Rails.application.routes.draw do

  get 'pages/readme'
  get 'pages/server'

  root 'posts#index'

  resources :posts 

  devise_for :users, controllers: {
  	registrations: 'users/registrations'
  }
  resources :users # POST /users is overriden by devise

  if Rails.env.development? || Rails.env.test?
	get '/ping', to: ->(env) { [204, {}, ['']] }
	get '/flash', {controller: :dev, action: :mock_flash}
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_rich_text :body
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :rememberable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :validatable, :lockable
         # TODO add confirmable, omniauthable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dev_controller.rb
class DevController < ApplicationController
  def mock_flash
    flash.notice = "Mock Notice!"
    flash.alert = "Mock Alert!"
    redirect_to root_url
  end

  def mock_mailer
    head :unimplemented
  end

  def mock_stream
    head :unimplemented
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def readme
	@readme = RDiscount.new(File.read( Rails.root.join('README.md') )).to_html
  end

  def server
    @server_info = `rails about`
    @routes_info = `rails routes`
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
		#format.turbo_stream
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :permanent, :user_id)
    end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :admin)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dev_helper.rb
module DevHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/dev/mock_flash.html.erb
<h1>Dev#mock_flash</h1>
<p>You should be redirected to index with a notice and alert flash message.</p>

app/views/dev/mock_mailer.html.erb
<h1>Dev#mock_mailer</h1>
<p>Unimplemented</p>

app/views/dev/mock_stream.html.erb
<h1>Dev#mock_stream</h1>
<p>Unimplemented</p>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yarb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

	<script type="text/javascript" defer>
		var toastElList = [].slice.call(document.querySelectorAll('.toast'))
		var toastList = toastElList.map(function (toastEl) {
		  return new bootstrap.Toast(toastEl, option)
		})
	</script>
  </head>

  <body class="container-fluid">
    <div class="container">
    <!-- todo: fix indenting -->
    <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none fs-2">
        <i class="bi bi-gem text-danger"></i>
      </a>

      <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
        <li><a href="<%= root_url %>" class="nav-link px-2 link-secondary">Home</a></li>
        <li><a href="<%= users_url %>" class="nav-link px-2 link-dark">Users</a></li>
        <li><a href="<%= posts_url %>" class="nav-link px-2 link-dark">Posts</a></li>
        <li><a href="<%= pages_readme_url %>" class="nav-link px-2 link-dark">Readme</a></li>
        <li><a href="<%= pages_server_url %>" class="nav-link px-2 link-dark">Server</a></li>
      </ul>

      <div class="col-md-3 text-end">
        <% if user_signed_in? %>
		  <%= link_to "Sign-out", destroy_user_session_url, method: :delete, class: "btn btn-outline-danger me-2" %>
		  <%= link_to "Profile", current_user, class: "btn btn-success" %>
        <% else %>
          <a href="<%= new_user_session_url %>" role="button" class="btn btn-outline-primary me-2">Login</a>
          <a href="<%= new_user_registration_url %>" role="button" class="btn btn-primary">Sign-up</a>
        <% end %>
      </div>
    </header>
    </div>

	<div class="container">
      <%= yield %>
    </div>

	<div id="toasts" class="toast-container position-fixed bottom-0 end-0 p-3" style="z-index: 10">
	  <% flash.each do |header, message| %>
		<%= render "shared/toast", title: header, message: message %>
	  <% end %>
	</div>

  </body>
</html>

app/views/pages/readme.html.erb
<h2 class="badge bg-primary">README.md</h2>

<%= sanitize @readme %>

app/views/pages/server.html.erb
<h3>$ rails about</h3>
<pre>
  <%= @server_info %>
</pre>
<br />

<h3>$ rails routes</h3>
<pre>
  <%= @routes_info %>
</pre>
<br />

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.rich_text_area :body %>
  </div>

  <div>
    <%= form.label :permanent, style: "display: block" %>
    <%= form.check_box :permanent %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>" class="container-fluid border rounded shadow mb-3 p-lg-5 p-3" style="height:100%;min-height:max-content;width:100%;max-width:100vw;">
  <h3 class="row"><%= post.title %></h3>

  <div class="row">
    <p class="text-muted">
      Authored <%= post.created_at.strftime('%r %x') %> by <%= post.user.name %> | <%= link_to 'See more', post, class: 'text-success' %>
    </p>
  </div>

  <div class="row">
    <%= post.body %>
  </div>
</div>

app/views/posts/create.turbo_stream.erb
<%= turbo_stream.prepend "toasts", partial: "shared/toast", locals: { title: "Saved Post", message: "Good stuff." } %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<div class="row mb-3">
  <%= link_to "New post", new_post_path, class: 'btn btn-primary' %>
</div>

<div id="posts" class="row row-cols-lg-auto g-2 justify-content-around">
  <% @posts.each do |post| %>
    <div class="col">
      <%= render post %>
    </div>
  <% end %>
  <hr />
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>

app/views/shared/_toast.html.erb
<%# _toasts.html.erb %>
<%# param: title %>
<%# param: message %>

<div data-controller="toast" data-bs-delay="3000" class="toast hide fadein" role="alert" aria-live="assertive" aria-atomic="true">
  <div class="toast-header">
	<img src="https://cdn-icons-png.flaticon.com/512/108/108925.png" class="rounded me-2" alt="[]" width=30 />
	<strong class="me-auto"><%= title&.titleize %></strong>
	<small><%= Time.new.strftime("%x") %></small>
	<button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
  </div>
  <div class="toast-body">
	<%= message %>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :admin, style: "display: block" %>
    <%= form.check_box :admin %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Admin:</strong>
    <%= user.admin %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<div class="row justify-content-around mb-2">
  <h1 class="col">Users</h1>

  <div class="col-lg-2 col-md-3 col-4 d-flex align-items-center">
    <%= link_to "New user", new_user_path, class: 'btn btn-primary mx-auto' %>
  </div>
</div>

<div id="users" class="list-group">
  <% @users.each do |user| %>
    <% if user.admin %>
      <a href="<%= user_url(user) %>" class="list-group-item list-group-item-action list-group-item-primary">
		<%= user.name %>
		<span class="badge bg-dark text-light mx-2">Admin<span>
      </a>
    <% else %>
      <a href="<%= user_url(user) %>" class="list-group-item list-group-item-action list-group-item-info"><%= user.name %></a>
    <% end %>
  <% end %>
</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>